[2022-06-11 10:21:04,112] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:21:04,113] [builder.py:185]            [INFO]     |                                 Trakt Popular Collection in Movies                                 |
[2022-06-11 10:21:04,113] [builder.py:185]            [INFO]     |====================================================================================================|
[2022-06-11 10:21:04,114] [builder.py:186]            [INFO]     |                                                                                                    |
[2022-06-11 10:21:04,114] [builder.py:191]            [INFO]     |=============================== Validating Trakt Popular Attributes ================================|
[2022-06-11 10:21:04,115] [builder.py:212]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,115] [builder.py:213]            [DEBUG]    | Validating Method: template                                                                        |
[2022-06-11 10:21:04,116] [meta.py:103]               [DEBUG]    | Value: [{'value': ['popular'], 'custom': ['popular'], 'key_name': 'Popular', 'key': 'popular', 'name': 'trakt'}, {'value': ['popular'], 'custom': ['popular'], 'key_name': 'Popular', 'key': 'popular', 'name': 'customsync'}, {'value': ['popular'], 'custom': ['popular'], 'key_name': 'Popular', 'key': 'popular', 'name': 'chart_shared'}] |
[2022-06-11 10:21:04,123] [builder.py:437]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,124] [builder.py:438]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-06-11 10:21:04,124] [builder.py:442]            [DEBUG]    | Value: sync                                                                                        |
[2022-06-11 10:21:04,124] [builder.py:582]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,125] [builder.py:583]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-06-11 10:21:04,125] [builder.py:584]            [DEBUG]    | Value: custom                                                                                      |
[2022-06-11 10:21:04,125] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,127] [builder.py:604]            [DEBUG]    | Validating Method: label                                                                           |
[2022-06-11 10:21:04,129] [builder.py:605]            [DEBUG]    | Value: Trakt                                                                                       |
[2022-06-11 10:21:04,129] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,130] [builder.py:604]            [DEBUG]    | Validating Method: trakt_chart                                                                     |
[2022-06-11 10:21:04,130] [builder.py:605]            [DEBUG]    | Value: {'chart': 'popular', 'limit': 100}                                                          |
[2022-06-11 10:21:04,134] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,135] [builder.py:604]            [DEBUG]    | Validating Method: summary                                                                         |
[2022-06-11 10:21:04,135] [builder.py:605]            [DEBUG]    | Value: A collection of Trakt's Weekly movie List                                                   |
[2022-06-11 10:21:04,136] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,136] [builder.py:604]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-06-11 10:21:04,136] [builder.py:605]            [DEBUG]    | Value: !01_Trakt Popular                                                                           |
[2022-06-11 10:21:04,137] [builder.py:600]            [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:04,137] [builder.py:604]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-06-11 10:21:04,138] [builder.py:605]            [DEBUG]    | Value: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/chart/Trakt%20Popular.jpg |
[2022-06-11 10:21:05,375] [plex.py:742]               [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:05,376] [plex.py:745]               [DEBUG]    | Looking for: Trakt Popular                                                                         |
[2022-06-11 10:21:05,377] [builder.py:764]            [INFO]     |                                                                                                    |
[2022-06-11 10:21:05,377] [builder.py:765]            [INFO]     | Validation Successful                                                                              |
[2022-06-11 10:21:05,378] [plex_meta_manager.py:539]  [INFO]     |                                                                                                    |
[2022-06-11 10:21:05,379] [plex_meta_manager.py:541]  [INFO]     |================================= Running Trakt Popular Collection =================================|
[2022-06-11 10:21:05,379] [plex_meta_manager.py:553]  [INFO]     |                                                                                                    |
[2022-06-11 10:21:05,380] [plex_meta_manager.py:554]  [INFO]     | Sync Mode: sync                                                                                    |
[2022-06-11 10:21:05,380] [plex_meta_manager.py:557]  [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:05,381] [plex_meta_manager.py:558]  [DEBUG]    | Builder: trakt_chart: {'chart': 'popular', 'limit': 100, 'time_period': None}                      |
[2022-06-11 10:21:05,381] [plex_meta_manager.py:559]  [INFO]     |                                                                                                    |
[2022-06-11 10:21:05,382] [trakt.py:490]              [INFO]     | Processing Trakt Chart: 100 Popular Movies                                                         |
[2022-06-11 10:21:06,650] [builder.py:1507]           [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:06,651] [builder.py:1508]           [DEBUG]    | 100 IDs Found: [(293660, 'tmdb'), (118340, 'tmdb'), (155, 'tmdb'), (27205, 'tmdb'), (24428, 'tmdb'), (157336, 'tmdb'), (284052, 'tmdb'), (263115, 'tmdb'), (603, 'tmdb'), (297762, 'tmdb'), (297761, 'tmdb'), (271110, 'tmdb'), (329865, 'tmdb'), (283995, 'tmdb'), (19995, 'tmdb'), (1726, 'tmdb'), (140607, 'tmdb'), (277834, 'tmdb'), (120, 'tmdb'), (286217, 'tmdb'), (299536, 'tmdb'), (315635, 'tmdb'), (109445, 'tmdb'), (550, 'tmdb'), (259316, 'tmdb'), (330459, 'tmdb'), (106646, 'tmdb'), (269149, 'tmdb'), (324552, 'tmdb'), (245891, 'tmdb'), (284053, 'tmdb'), (49026, 'tmdb'), (122, 'tmdb'), (99861, 'tmdb'), (76341, 'tmdb'), (68718, 'tmdb'), (121, 'tmdb'), (274870, 'tmdb'), (100402, 'tmdb'), (671, 'tmdb'), (13, 'tmdb'), (150540, 'tmdb'), (11, 'tmdb'), (102899, 'tmdb'), (680, 'tmdb'), (299534, 'tmdb'), (278, 'tmdb'), (272, 'tmdb'), (284054, 'tmdb'), (209112, 'tmdb'), (207703, 'tmdb'), (12, 'tmdb'), (10681, 'tmdb'), (14160, 'tmdb'), (419430, 'tmdb'), (135397, 'tmdb'), (1771, 'tmdb'), (8587, 'tmdb'), (105, 'tmdb'), (68721, 'tmdb'), (10138, 'tmdb'), (246655, 'tmdb'), (475557, 'tmdb'), (339403, 'tmdb'), (1891, 'tmdb'), (137113, 'tmdb'), (70160, 'tmdb'), (672, 'tmdb'), (862, 'tmdb'), (10195, 'tmdb'), (673, 'tmdb'), (585, 'tmdb'), (49051, 'tmdb'), (9806, 'tmdb'), (383498, 'tmdb'), (328111, 'tmdb'), (177572, 'tmdb'), (16869, 'tmdb'), (674, 'tmdb'), (12445, 'tmdb'), (293167, 'tmdb'), (1892, 'tmdb'), (302946, 'tmdb'), (20352, 'tmdb'), (281957, 'tmdb'), (76338, 'tmdb'), (75656, 'tmdb'), (324786, 'tmdb'), (675, 'tmdb'), (807, 'tmdb'), (101299, 'tmdb'), (22, 'tmdb'), (127380, 'tmdb'), (127585, 'tmdb'), (767, 'tmdb'), (333339, 'tmdb'), (381288, 'tmdb'), (210577, 'tmdb'), (353486, 'tmdb'), (12444, 'tmdb')] |
[2022-06-11 10:21:06,652] [builder.py:1509]           [DEBUG]    |                                                                                                    |
[2022-06-11 10:21:06,678] [builder.py:2009]           [INFO]     |                                                                                                    |
[2022-06-11 10:21:06,679] [builder.py:2010]           [INFO]     |================================ Adding to Trakt Popular Collection ================================|
[2022-06-11 10:21:06,679] [builder.py:2011]           [INFO]     |                                                                                                    |
[2022-06-11 10:21:06,680] [builder.py:2025]           [INFO]     |  1/24 | Trakt Popular Collection | + | The Dark Knight (2008)                                      |
[2022-06-11 10:21:08,149] [builder.py:2025]           [INFO]     |  2/24 | Trakt Popular Collection | + | The Matrix (1999)                                           |
[2022-06-11 10:21:09,671] [builder.py:2025]           [INFO]     |  3/24 | Trakt Popular Collection | + | Avatar (2009)                                               |
[2022-06-11 10:21:17,280] [builder.py:2025]           [INFO]     |  4/24 | Trakt Popular Collection | + | The Lord of the Rings: The Fellowship of the Ring (2001)    |
[2022-06-11 10:21:19,335] [builder.py:2025]           [INFO]     |  5/24 | Trakt Popular Collection | + | Fight Club (1999)                                           |
[2022-06-11 10:21:20,736] [builder.py:2025]           [INFO]     |  6/24 | Trakt Popular Collection | + | The Lord of the Rings: The Return of the King (2003)        |
[2022-06-11 10:21:22,653] [builder.py:2025]           [INFO]     |  7/24 | Trakt Popular Collection | + | The Lord of the Rings: The Two Towers (2002)                |
[2022-06-11 10:21:23,357] [builder.py:2025]           [INFO]     |  8/24 | Trakt Popular Collection | + | Forrest Gump (1994)                                         |
[2022-06-11 10:21:24,799] [builder.py:2025]           [INFO]     |  9/24 | Trakt Popular Collection | + | Star Wars (1977)                                            |
[2022-06-11 10:21:26,033] [builder.py:2025]           [INFO]     | 10/24 | Trakt Popular Collection | + | Pulp Fiction (1994)                                         |
[2022-06-11 10:21:26,387] [builder.py:2025]           [INFO]     | 11/24 | Trakt Popular Collection | + | The Shawshank Redemption (1994)                             |
[2022-06-11 10:21:26,986] [builder.py:2025]           [INFO]     | 12/24 | Trakt Popular Collection | + | Batman Begins (2005)                                        |
[2022-06-11 10:21:27,914] [builder.py:2025]           [INFO]     | 13/24 | Trakt Popular Collection | + | Finding Nemo (2003)                                         |
[2022-06-11 10:21:28,828] [builder.py:2025]           [INFO]     | 14/24 | Trakt Popular Collection | + | WALL·E (2008)                                               |
[2022-06-11 10:21:29,475] [builder.py:2025]           [INFO]     | 15/24 | Trakt Popular Collection | + | Up (2009)                                                   |
[2022-06-11 10:21:30,031] [builder.py:2025]           [INFO]     | 16/24 | Trakt Popular Collection | + | Back to the Future (1985)                                   |
[2022-06-11 10:21:30,295] [builder.py:2025]           [INFO]     | 17/24 | Trakt Popular Collection | + | Star Wars: Episode V - The Empire Strikes Back (1980)       |
[2022-06-11 10:21:30,676] [builder.py:2025]           [INFO]     | 18/24 | Trakt Popular Collection | + | Toy Story (1995)                                            |
[2022-06-11 10:21:30,923] [builder.py:2025]           [INFO]     | 19/24 | Trakt Popular Collection | + | Monsters, Inc. (2001)                                       |
[2022-06-11 10:22:31,274] [plex_meta_manager.py:668]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
                                                                 |     six.raise_from(e, None)
                                                                 |   File "<string>", line 3, in raise_from
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
                                                                 |     httplib_response = conn.getresponse()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
                                                                 |     response.begin()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 312, in begin
                                                                 |     version, status, reason = self._read_status()
                                                                 |   File "/usr/lib/python3.8/http/client.py", line 273, in _read_status
                                                                 |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                 |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
                                                                 |     return self._sock.recv_into(b)
                                                                 | socket.timeout: timed out
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
                                                                 |     resp = conn.urlopen(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
                                                                 |     retries = retries.increment(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
                                                                 |     raise six.reraise(type(error), error, _stacktrace)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
                                                                 |     httplib_response = self._make_request(
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
                                                                 |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
                                                                 |   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
                                                                 |     raise ReadTimeoutError(
                                                                 | urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "plex_meta_manager.py", line 570, in run_collection
                                                                 |     items_added, items_unchanged = builder.add_to_collection()
                                                                 |   File "/root/Plex-Meta-Manager/modules/builder.py", line 2032, in add_to_collection
                                                                 |     self.library.alter_collection(item, name, smart_label_collection=self.smart_label_collection)
                                                                 |   File "/root/Plex-Meta-Manager/modules/plex.py", line 650, in alter_collection
                                                                 |     field = next((f for f in item.fields if f.name == "collection"), None)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 483, in __getattribute__
                                                                 |     self._reload(_overwriteNone=False)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/base.py", line 357, in _reload
                                                                 |     data = self._server.query(key)
                                                                 |   File "/usr/lib/python3.8/site-packages/plexapi/server.py", line 696, in query
                                                                 |     response = method(url, headers=headers, timeout=timeout, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
                                                                 |     return self.request('GET', url, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
                                                                 |     resp = self.send(prep, **send_kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
                                                                 |     r = adapter.send(request, **kwargs)
                                                                 |   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
                                                                 |     raise ReadTimeout(e, request=request)
                                                                 | requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
                                                                 | 
[2022-06-11 10:22:31,302] [plex_meta_manager.py:669]  [ERROR]    | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)
[2022-06-11 10:22:31,303] [plex_meta_manager.py:674]  [INFO]     | 
[2022-06-11 10:22:31,303] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
[2022-06-11 10:22:31,303] [plex_meta_manager.py:675]  [INFO]     |                                 Finished Trakt Popular Collection                                  |
[2022-06-11 10:22:31,304] [plex_meta_manager.py:675]  [INFO]     |                                    Collection Run Time: 0:01:27                                    |
[2022-06-11 10:22:31,304] [plex_meta_manager.py:675]  [INFO]     |====================================================================================================|
